server:
  port: 8088
---
spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: settlement
          uri: http://localhost:8081
          predicates:
            - Path=/settlements/**

      #        - id: pet-front
      #          uri: http://localhost:3000
      #          predicates:
      #            - Path=/**

      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true
---
spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: settlement
          uri: http://settlement:8080
          predicates:
            - Path=/settlements/**

      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
